### ISSUE TITLE
Blog Plugin Not Working?

### ISSUE THREAD

**Issue by wragen22** [eudicots/Cactus#266]
Hello, enable the blog plugin, but then got a bunch of stuff spit back at me. Any idea?

`Traceback (most recent call last):
  File "/usr/local/bin/cactus", line 9, in <module>
    load_entry_point('Cactus==3.3.3', 'console_scripts', 'cactus')()
  File "/Library/Python/2.7/site-packages/Cactus-3.3.3-py2.7.egg/cactus/cli.py", line 159, in cli_entrypoint
    main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/Cactus-3.3.3-py2.7.egg/cactus/cli.py", line 155, in main
    ns.target(**kwargs)
  File "/Library/Python/2.7/site-packages/Cactus-3.3.3-py2.7.egg/cactus/cli.py", line 65, in serve
    site.serve(port=port, browser=browser)
  File "/Library/Python/2.7/site-packages/Cactus-3.3.3-py2.7.egg/cactus/site.py", line 438, in serve
    self.build()
  File "/Library/Python/2.7/site-packages/Cactus-3.3.3-py2.7.egg/cactus/site.py", line 243, in build
    self.plugin_manager.preBuild(self)
  File "/Library/Python/2.7/site-packages/Cactus-3.3.3-py2.7.egg/cactus/plugin/manager.py", line 31, in call
    _meth(*args, **kwargs)
  File "/Users/bradwrage/sites/bradwrage/plugins/blog.py", line 54, in preBuild
    postContext['body'] = getNode(get_template(page.path), name="body")
  File "/Users/bradwrage/sites/bradwrage/plugins/blog.py", line 23, in getNode
    return getNode(node.nodelist, context, name)
  File "/Users/bradwrage/sites/bradwrage/plugins/blog.py", line 21, in getNode
    return node.render(context)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/defaulttags.py", line 100, in render
    filtered = self.filter_expr.resolve(context)
  File "/Library/Python/2.7/site-packages/Django-1.6.11-py2.7.egg/django/template/base.py", line 613, in resolve
    new_obj = func(obj, *arg_vals)
  File "build/bdist.macosx-10.12-intel/egg/django_markwhat/templatetags/markup.py", line 61, in markdown
ImportError: No module named markdown`

**Comment by wragen22** [comment]
Any thoughts here?

**Comment by rob-weiss** [comment]
Hi wragen22,

it seems like your missing the Python Markdown package.

Copy the following into your command line (Terminal App) and press enter to install the Python Markdown package.

```
easy_install markdown
```
